include: package:flutter_lints/flutter.yaml

linter:
  rules:
    # Style
    - prefer_const_constructors
    - prefer_const_declarations
    - prefer_final_fields
    - prefer_final_locals
    - unnecessary_const
    - unnecessary_new
    
    # Errors
    - avoid_print
    - avoid_relative_lib_imports
    - avoid_unnecessary_containers
    - prefer_is_empty
    - prefer_is_not_empty
    
    # Readability
    - always_declare_return_types
    - annotate_overrides
    - avoid_empty_else
    - avoid_init_to_null
    - avoid_return_types_on_setters
    - avoid_void_async
    - cancel_subscriptions
    - sized_box_for_whitespace
    - use_key_in_widget_constructors

# Analyzer options
analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "**/*.mocks.dart"
    - build/**
    - android/**
    - ios/**
    - linux/**
    - web/**
  
  errors:
    invalid_annotation_target: ignore
  
  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: true
