import 'package:uniflow/core/api/tulsu_api.dart';

/// Fake marks shown in demo mode instead of calling the progress API.
/// Tone matches the demo schedule: plausible subjects, joke teachers,
/// a mix of attested / not-attested across several terms.
List<MarksItem> buildDemoMarks() => const [
      // ── Term 1 ──
      MarksItem(
        term: '1',
        discipline: 'Математический анализ',
        mark: '5',
        markTitle: 'Отлично',
        teacherMark: 'Безупречно',
        retake: '',
        recredit: false,
      ),
      MarksItem(
        term: '1',
        discipline: 'Информатика',
        mark: '4',
        markTitle: 'Хорошо',
        teacherMark: 'Хорошо',
        retake: '',
        recredit: false,
      ),
      MarksItem(
        term: '1',
        discipline: 'История',
        mark: '',
        markTitle: '',
        teacherMark: '',
        retake: '',
        recredit: false,
      ),
      // ── Term 2 ──
      MarksItem(
        term: '2',
        discipline: 'Физика',
        mark: '4',
        markTitle: 'Хорошо',
        teacherMark: 'Убедительно',
        retake: '',
        recredit: false,
      ),
      MarksItem(
        term: '2',
        discipline: 'Программирование',
        mark: '5',
        markTitle: 'Отлично',
        teacherMark: 'Идеально',
        retake: '',
        recredit: false,
      ),
      MarksItem(
        term: '2',
        discipline: 'Физическая культура',
        mark: 'Зачёт',
        markTitle: 'Зачёт',
        teacherMark: 'Живой пример',
        retake: '',
        recredit: false,
      ),
      MarksItem(
        term: '2',
        discipline: 'Английский язык',
        mark: '',
        markTitle: '',
        teacherMark: '',
        retake: '',
        recredit: false,
      ),
      // ── Term 3 (current) ──
      MarksItem(
        term: '3',
        discipline: 'Базы данных',
        mark: '5',
        markTitle: 'Отлично',
        teacherMark: 'Так держать',
        retake: '',
        recredit: false,
      ),
      MarksItem(
        term: '3',
        discipline: 'Веб-разработка',
        mark: '4',
        markTitle: 'Хорошо',
        teacherMark: 'Красиво',
        retake: '',
        recredit: false,
      ),
      MarksItem(
        term: '3',
        discipline: 'Дискретная математика',
        mark: '3',
        markTitle: 'Удовлетворительно',
        teacherMark: 'Проходит',
        retake: '',
        recredit: false,
      ),
      MarksItem(
        term: '3',
        discipline: 'Теория вероятностей',
        mark: '',
        markTitle: '',
        teacherMark: '',
        retake: '',
        recredit: false,
      ),
      MarksItem(
        term: '3',
        discipline: 'Математика (пример отменён)',
        mark: '',
        markTitle: '',
        teacherMark: '',
        retake: 'Пересдача 25.02',
        recredit: true,
      ),
    ];
